CREATE OR REPLACE TABLE TESTDB.ECOMMERCE.INVOICES AS( SELECT DISTINCT CUSTOMERID, COUNTRY, INVOICEDATE, INVOICENO
               FROM TESTDB.ECOMMERCE.DATA
              );

CREATE OR REPLACE TABLE TESTDB.ECOMMERCE.ITEMS AS ( SELECT DISTINCT STOCKCODE, DESCRIPTION, UNITPRICE,QUANTITY, INVOICENO
               FROM TESTDB.ECOMMERCE.DATA
              );

-- expected n rows 25905
SELECT COUNT(*) FROM INVOICES;

-- expected n rows 531876
SELECT COUNT(*) FROM ITEMS;
